name: salon
description: "Auto Salon Management App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'  # Исправляем версию SDK

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  dio: ^5.3.2
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^8.0.0
  json_annotation: ^4.9.0  # Обновляем версию
  go_router: ^12.1.3
  provider: ^6.1.1
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  flutter_dotenv: ^5.0.2
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/